# Generated by Django 4.1.3 on 2022-11-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='code',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
