# Generated by Django 4.1.3 on 2022-11-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_main_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busnumber', models.CharField(default='', max_length=3)),
                ('busname', models.CharField(default='', max_length=50)),
                ('delaymessage', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('favourites', models.CharField(blank=True, max_length=8, null=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
