# Generated by Django 4.1.3 on 2022-11-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_main_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesListField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites_list', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='main',
            name='code',
        ),
    ]
