# Generated by Django 4.1.3 on 2022-11-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ttcdata_user_remove_main_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTCUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
