# Generated by Django 4.1.3 on 2022-11-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_busalert_signup_delete_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='favourites',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
