# Generated by Django 4.1.3 on 2022-11-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_signup_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busalert',
            name='busname',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='busalert',
            name='busnumber',
            field=models.CharField(default='', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
