# Generated by Django 4.1.3 on 2022-11-06 03:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_ttcuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttcuser',
            name='email',
        ),
        migrations.AddField(
            model_name='ttcuser',
            name='favourites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='ttcuser',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
