# Generated by Django 4.1.3 on 2022-11-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_busalert_busname_alter_busalert_busnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
